version: '3'
services:
  db:
    image: postgres
    environment: &PG_ENV
        POSTGRES_USER: test_chest
        POSTGRES_PASSWORD: postgres_password
    volumes:
      - ./db:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "3456:80"
    environment:
        <<: *PG_ENV
    depends_on:
      - db
    volumes:
      - ./test_chest/migrations:/var/lib/test-chest-env/lib/python3.5/site-packages/test_chest/migrations
