version: '3'
services:
  db:
    image: postgres
    environment: &PG_ENV
        POSTGRES_USER: test_chest
        POSTGRES_PASSWORD: postgres_password
    volumes:
      - ${PWD}/db:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "3456:80"
    environment:
        <<: *PG_ENV
    depends_on:
      - db
    volumes:
      - ${PWD}/test_chest/migrations:/usr/local/lib/python3.5/dist-packages/test_chest/migrations/
