FROM python:3.5-alpine as build

RUN apk update && \
    apk add git postgresql-dev build-base && \
    rm /var/cache/* -rf

RUN pip install -U pip setuptools virtualenv tox pbr && \
    rm /root/.cache/pip/wheels/* -rf

RUN virtualenv /var/lib/test-chest-env

COPY requirements.txt /tmp/
RUN /var/lib/test-chest-env/bin/pip install -r /tmp/requirements.txt && \
    rm /root/.cache/pip/wheels/* -rf

COPY . /tmp/test-chest-install-files
WORKDIR /tmp/test-chest-install-files
RUN python setup.py sdist && /var/lib/test-chest-env/bin/pip install dist/*
RUN tox && rm .tox -rf

FROM python:3.5-alpine

RUN apk update && \
    apk add postgresql-dev supervisor && \
    rm /var/cache/* -rf

COPY --from=build /var/lib/test-chest-env /var/lib/test-chest-env

COPY files/supervisor /etc/supervisor
COPY files/run_server_dev.py /tmp/

ENTRYPOINT ["/var/lib/test-chest-env/bin/python", "-u", "/tmp/run_server_dev.py"]
