# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('classname', models.CharField(max_length=255)),
                ('file', models.CharField(max_length=255)),
                ('line', models.PositiveIntegerField()),
                ('time', models.FloatField()),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('failure_message', models.TextField(blank=True, null=True)),
                ('traceback', models.TextField(blank=True, null=True)),
                ('tags', models.ManyToManyField(related_name='tests', to='test_chest.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('time', models.FloatField()),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='testcase',
            name='testsuite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='test_chest.TestSuite'),
        ),
    ]
